#!/usr/bin/env python3
"""M7t synthetic readout test (docs/rl_m7t_synthetic_prerequisite_review_2026-09-29.md, section 4, as revised by the user).

Zero optimizer steps. No BattleShip, no native tick, no new network: the saved T networks of the registered
prerequisite run (logs/m7t_synth_prereq/s{0,1,2}_T.pt) are only evaluated. The harness rl/tools/m7t_synthetic_prereq.py
is imported unchanged (world, data, observation builder, networks); the registered FAIL is not touched.

    python rl/tools/m7t_synthetic_readout.py pin --out DIR     # writes DIR/protocol.json (write-once) with its hash
    python rl/tools/m7t_synthetic_readout.py run --out DIR     # refuses unless DIR/protocol.json matches PROTOCOL

One controlled change: the goal distance used by the greedy rule, from the goal node d(T(z, a), w(G)) (original readout,
"O") to min over at most 32 representative full states g_i of cell G of d(T(z, a), z(g_i)) ("R"). Representatives come
only from the frozen training archive (training-split rows of the registered data), in a fixed hash order; evaluation
trajectories are never used. Action set, tie-breaking (torch.argmin, lowest index), start, goals, horizon and batching
are unchanged. The original readout must reproduce the saved registered episodes word for word before R is evaluated.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "rl" / "tools"))
sys.path.insert(0, str(REPO / "rl"))

import m7t_synthetic_prereq as m  # noqa: E402  (unchanged harness)
import m7t_synthetic_posthoc as ph  # noqa: E402  (corrected memory probe only)

RUN = REPO / "logs" / "m7t_synth_prereq"

PROTOCOL: Dict[str, Any] = {
    "id": "m7t_synth_readout_v1",
    "design": "docs/rl_m7t_synthetic_prerequisite_review_2026-09-29.md section 4, revised by the user 2026-09-29",
    "inputs_sha256": {
        "logs/m7t_synth_prereq/s0_T.pt": "d83e92bfd9ede17391af5fe32b078e28ffc75d04e1dfec4940a7a53a744d8ba9",
        "logs/m7t_synth_prereq/s1_T.pt": "a05e70692ac0fb793122a491ff71296aa9c2073a6b1bf46701a777af9a86c3e4",
        "logs/m7t_synth_prereq/s2_T.pt": "c434c466800ec28270effb24c0e34b052ba2b7db4873cd84d34372c2de88de1f",
        "logs/m7t_synth_prereq/results.json": "3cd6526cece7d75a649539444d376f48e38161f66497e7ce18a3cd565f868b6c",
        "logs/m7t_synth_prereq/s0_episodes.json.gz": "8b5eff096f4131ac2841876203e0fd1847a6e46cf521cbf320f69cf2aad1eeb0",
        "logs/m7t_synth_prereq/s1_episodes.json.gz": "e4c70194e9e05a339308ae8ee495d64e6cd267d621528605e7dac5e143afc4b3",
        "logs/m7t_synth_prereq/s2_episodes.json.gz": "e895496293bb9e93ccb6fc63c1b493f1938131da651169fa112e375f9646b369",
        "rl/tools/m7t_synthetic_prereq.py": "cb3ad35abfdb1644f6dec03e359fa8387033f1dca602a16069cfa958e9b1f1c2",
        "rl/m7s_goal.py": "5fcd33f96bc4c1b955306736f595939f1eb7be77209c1be06b5dae05ac1686d5",
    },
    "seeds": [0, 1, 2],
    "goals": "every registered rare goal E of results.json (16 + 20 + 20 = 56), in registered order; one greedy "
             "episode per goal and readout from the fixed start; budget 3,600 ticks; success = first valid reach of "
             "the cell (cell and contact), as registered",
    "readout_O": "d(T(z_t, a), w(G)) with the saved goal encoder (the registered rule)",
    "readout_R": "min over the representatives g_i of G of d(T(z_t, a), z(g_i)); z(g_i) = saved state encoder applied to "
                 "the representative's full observation",
    "representatives": {
        "pool": "training-split state rows (the 108 training episodes of the registered data regenerated by seed) whose "
                "valid cell code equals G; held-out episodes, evaluation episodes and their states are never in the "
                "pool",
        "order": "ascending sha256('m7t_readout|rep|seed|episode_id|k'), k = row index within the episode",
        "max": 32,
        "fail": "any goal with no representative, or any representative outside the pool -> stop, no interpretation",
    },
    "fixed": "72 Track 1-shaped words; torch.argmin (first minimum = lowest index); batch = all goals of a seed in "
             "registered order, finished episodes dropped exactly as in the harness loop; torch threads 6; no_grad; "
             "no optimizer object; the same predicted next latents T(z, a) feed both readouts",
    "baseline_reproduction": "readout O re-evaluated must give, for every one of the 56 goals, word sequences, end "
                             "reasons and reach ticks identical to the saved registered T_rare episodes; any mismatch -> "
                             "stop before R is evaluated, no interpretation",
    "diagnostics": {
        "near_zero": "tick t with readout distance D_t = D(z_t, G) <= 1.0 while the state at t is not in G",
        "false_arrival": "a near-zero tick not followed by the reach within 120 ticks",
        "true_remaining": "exact BFS ticks from the state at the first near-zero tick of each failed episode to G",
        "horizon_exhaust": "failed episode that reaches the 3,600-tick budget with no near-zero tick",
        "split": "airborne vs ground goals, reported only",
    },
    "decision": {
        "primary": "n_R = rare goals reached with readout R, pooled over the 3 seeds (56 goals); n_O the reproduced "
                   "original count; paired per goal: gains g+ (R only), losses g- (O only)",
        "confirm": "n_R >= 42 and g- <= 3 and n_R(seed) >= n_O(seed) in every seed",
        "reject": "n_R <= n_O + 4",
        "inconclusive": "otherwise",
        "justification": "42 = 75 % of 56, i.e. recovering half of the 28 control failures (the review's 36/48 = 75 % "
                         "scaled to all goals); g- <= 3 so a gain is not bought by trading previously reached goals; no "
                         "seed worse so one seed cannot carry it; reject at <= control + 4 because goal outcomes are "
                         "dependent (one different route reaches several clustered goals) and 4 is the twin margin the "
                         "gate rule already uses; the exact sign test on (g+, g-) is reported, never decisive",
        "claim_if_confirm": "readout R improves these saved synthetic policies' returns to their registered rare goals; "
                            "it does not validate training without goal nodes, prove optimizer convergence, or "
                            "authorise any Mario gate",
    },
    "caps": {"wall_s": 7200, "peak_private_mb": 2048, "optimizer_steps": 0,
             "breach": "stop, status incomplete, no interpretation"},
}


def canon(o: Any) -> bytes:
    return json.dumps(o, sort_keys=True, separators=(",", ":")).encode()


PROTOCOL_DIGEST = hashlib.sha256(canon(PROTOCOL)).hexdigest()


def sha_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


class Stop(RuntimeError):
    pass


class Caps:
    def __init__(self) -> None:
        self.t0 = time.perf_counter()

    def check(self, where: str) -> None:
        w = time.perf_counter() - self.t0
        mem = ph.mem()
        if w > PROTOCOL["caps"]["wall_s"]:
            raise Stop(f"wall cap exceeded at {where}: {w:.0f} s")
        if mem.get("peak_private_mb", 0.0) > PROTOCOL["caps"]["peak_private_mb"]:
            raise Stop(f"memory cap exceeded at {where}: {mem}")


def params_digest(nets) -> str:
    h = hashlib.sha256()
    for k, v in sorted(nets.state_dict().items()):
        h.update(k.encode())
        h.update(v.detach().cpu().numpy().tobytes())
    return h.hexdigest()


def select_reps(sd: m.SeedData, goals: Sequence[int]) -> Dict[int, List[int]]:
    """Representative state rows per goal: training-split rows only, fixed hash order, at most 32."""
    train_eps = set(sd.train)
    ep_of_row = np.zeros(len(sd.codes), np.int64)
    k_of_row = np.zeros(len(sd.codes), np.int64)
    for e, ep in enumerate(sd.eps):
        rows = sd.off[e] + np.arange(ep["T"] + 1)
        ep_of_row[rows] = e
        k_of_row[rows] = np.arange(ep["T"] + 1)
    out: Dict[int, List[int]] = {}
    for g in goals:
        rows = sd.train_rows[sd.codes[sd.train_rows] == g]
        keyed = sorted(rows.tolist(), key=lambda r: hashlib.sha256(
            f"m7t_readout|rep|{sd.seed}|{sd.eps[ep_of_row[r]]['id']}|{k_of_row[r]}".encode()).hexdigest())
        sel = keyed[:PROTOCOL["representatives"]["max"]]
        if not sel:
            raise Stop(f"seed {sd.seed}: goal {m.code_to_cell(g)} has no representative in the training archive")
        for r in sel:
            if ep_of_row[r] not in train_eps or sd.recs["dead"][r] or sd.codes[r] != g:
                raise Stop(f"seed {sd.seed}: representative row {r} outside the pool")
        out[int(g)] = [int(r) for r in sel]
    return out


def evaluate(torch, nets, goal_codes: Sequence[int], readout: str, rep_z: Optional[Dict[int, Any]], caps: Caps,
             budget: int = m.HORIZON) -> List[Dict[str, Any]]:
    """The harness's greedy batched loop (run_episodes) with only the scoring readout switchable; per tick it records
    the readout distance of the current state and, for near-zero ticks, the dynamic state."""
    B = len(goal_codes)
    r = m.initial_record(m.start_state(B))
    gw = nets.w(torch.from_numpy(m.goal_feats(np.asarray(goal_codes))))
    allw = torch.arange(72)
    active = np.ones(B, bool)
    reach = np.full(B, -1, np.int64)
    end = ["budget"] * B
    words: List[List[int]] = [[] for _ in range(B)]
    dist: List[List[float]] = [[] for _ in range(B)]
    nz_state: List[Optional[Dict[str, int]]] = [None] * B
    nz_tick: List[Optional[int]] = [None] * B

    def readout_d(x, b_list):
        """Readout distance of latents x (rows ordered by b_list, each row one state) to each row's goal."""
        if readout == "O":
            return m_d(x, gw[b_list])
        vals = []
        for i, b in enumerate(b_list):
            reps = rep_z[int(goal_codes[b])]
            vals.append(m_d(x[i:i + 1].expand(len(reps), -1), reps).min())
        return torch.stack(vals)

    m_d = nets.d
    with torch.no_grad():
        for t in range(m.HORIZON + 1):
            ai = np.nonzero(active)[0]
            if len(ai) == 0:
                break
            if t % 200 == 0:
                caps.check(f"{readout} tick {t}")
            ob = m.build_obs(m.rec_take(r, ai))
            z = nets.z(torch.from_numpy(ob))
            dnow = readout_d(z, ai).numpy()
            for k, b in enumerate(ai):
                dist[b].append(float(dnow[k]))
                if nz_tick[b] is None and dnow[k] <= 1.0:
                    nz_tick[b] = t
                    nz_state[b] = {f: int(r[f][b]) for f in m.DYN}
            if t == m.HORIZON:
                break
            zr = z.repeat_interleave(72, dim=0)
            wds = allw.repeat(len(ai))
            pred = nets.T(zr, wds)
            if readout == "O":
                sc = m_d(pred, gw[ai].repeat_interleave(72, dim=0)).view(len(ai), 72)
            else:
                rows = []
                for k, b in enumerate(ai):
                    reps = rep_z[int(goal_codes[b])]
                    pk = pred[k * 72:(k + 1) * 72]
                    n = len(reps)
                    dd = m_d(pk.repeat_interleave(n, dim=0), reps.repeat(72, 1)).view(72, n)
                    rows.append(dd.min(dim=1).values)
                sc = torch.stack(rows)
            choice = torch.argmin(sc, dim=1)
            ch = choice.numpy().astype(np.int64)
            nr, dead = m.advance(m.rec_take(r, ai), ch)
            codes = m.cell_codes({k: nr[k] for k in m.DYN})
            for k, b in enumerate(ai):
                words[b].append(int(ch[k]))
            for key in m.REC:
                r[key][ai] = nr[key]
            for k, b in enumerate(ai):
                tick = t + 1
                if dead[k]:
                    active[b] = False
                    end[b] = "dead"
                elif codes[k] == goal_codes[b]:
                    active[b] = False
                    reach[b] = tick
                    end[b] = "reached"
                elif tick >= budget:
                    active[b] = False
                    end[b] = "budget"
    return [{"goal": int(goal_codes[b]), "cell": list(m.code_to_cell(int(goal_codes[b]))), "success": bool(reach[b] > 0),
             "reach": int(reach[b]), "end": end[b], "len": len(words[b]), "words": words[b], "dist": dist[b],
             "near_zero_tick": nz_tick[b], "near_zero_state": nz_state[b]} for b in range(B)]


def diagnose(eps: List[Dict[str, Any]]) -> None:
    for e in eps:
        d = np.array(e["dist"])
        nz = [t for t in range(len(d)) if d[t] <= 1.0]           # rows before the reach are never in G
        fa = [t for t in nz if not (e["success"] and e["reach"] <= t + 120)]
        e["near_zero_ticks"] = len(nz)
        e["false_arrival"] = bool(fa)
        e["first_false_arrival_tick"] = fa[0] if fa else None
        e["true_remaining_at_first_near_zero"] = None
        if not e["success"] and e["near_zero_state"] is not None:
            st = {k: np.array([v], np.int64) for k, v in e["near_zero_state"].items()}
            dd, _ = m.bfs(st, want={e["goal"]})
            e["true_remaining_at_first_near_zero"] = dd.get(e["goal"])
        e["horizon_exhaust"] = (not e["success"]) and e["end"] == "budget" and not nz
        e["min_dist"] = float(d.min()) if len(d) else None


def cmd_pin(out: Path) -> int:
    out.mkdir(parents=True, exist_ok=True)
    p = out / "protocol.json"
    if p.exists():
        raise SystemExit(f"{p} exists; the protocol is write-once")
    rec = {"utc": m.utc(), "protocol_digest": PROTOCOL_DIGEST, "tool_sha256_at_pin": sha_file(Path(__file__)),
           "protocol": PROTOCOL}
    p.write_text(json.dumps(rec, indent=1), encoding="utf-8")
    print(f"pinned {PROTOCOL_DIGEST} at {rec['utc']}")
    return 0


def cmd_run(out: Path) -> int:
    pin = json.loads((out / "protocol.json").read_text(encoding="utf-8"))
    if pin["protocol_digest"] != PROTOCOL_DIGEST or hashlib.sha256(canon(pin["protocol"])).hexdigest() != PROTOCOL_DIGEST:
        raise SystemExit("protocol digest differs from this tool's PROTOCOL: refusing")
    torch = m.torch_mod()
    caps = Caps()
    status: Dict[str, Any] = {"protocol_digest": PROTOCOL_DIGEST, "tool_sha256_at_run": sha_file(Path(__file__)),
                              "tool_sha256_at_pin": pin["tool_sha256_at_pin"], "started_utc": m.utc(), "phase": "inputs",
                              "memory": {}, "seeds": {}}

    def save(name: str = "result.json") -> None:
        status["wall_s"] = time.perf_counter() - caps.t0
        status["memory"]["end"] = ph.mem()
        (out / name).write_text(json.dumps(status, indent=1, default=float), encoding="utf-8")

    try:
        for rel, h in PROTOCOL["inputs_sha256"].items():
            if sha_file(REPO / rel) != h:
                raise Stop(f"input hash mismatch: {rel}")
        reg = json.loads((RUN / "results.json").read_text(encoding="utf-8"))
        data: Dict[int, Any] = {}
        # phase 1: data regeneration and representative selection (before any evaluation)
        status["phase"] = "selection"
        for s in PROTOCOL["seeds"]:
            sd = m.SeedData(s, m.REG["data"]["episodes"], m.HORIZON, m.REG["data"]["phase_a"], m.REG["data"]["held_out"])
            sres = reg["seeds"][str(s)]
            if len(sd.tr_src) != sres["transitions_train"] or len(sd.goal_nodes) != sres["goal_nodes"]:
                raise Stop(f"seed {s}: regenerated data differ from the registered run")
            goals = [m.cell_to_code(tuple(c)) for c in sres["E"]]
            saved = json.load(gzip.open(RUN / f"s{s}_episodes.json.gz", "rt", encoding="utf-8"))["T_rare"]
            if [e["goal"] for e in saved] != goals:
                raise Stop(f"seed {s}: saved T_rare goals differ from the registered E")
            for e in saved:
                if e["success"] and m.replay_reach(e["words"], e["goal"]) != e["reach"]:
                    raise Stop(f"seed {s}: a saved return does not replay in the regenerated world")
            reps = select_reps(sd, goals)
            status["seeds"][str(s)] = {"goals": len(goals), "representatives": {
                str(m.code_to_cell(g)): len(v) for g, v in reps.items()},
                "representative_digest": hashlib.sha256(canon({str(g): v for g, v in reps.items()})).hexdigest()}
            rep_obs = {g: sd.obs(np.array(v, np.int64)) for g, v in reps.items()}
            data[s] = (sd.mean.copy(), sd.std.copy(), goals, saved, rep_obs)
            del sd
            __import__("gc").collect()
            caps.check(f"selection seed {s}")
        status["memory"]["after_selection"] = ph.mem()
        save("result_partial.json")
        # phase 2: baseline reproduction with readout O (before R)
        status["phase"] = "baseline_reproduction"
        nets_by: Dict[int, Any] = {}
        for s in PROTOCOL["seeds"]:
            mean, std, goals, saved, rep_obs = data[s]
            nets = m.make_nets(torch, mean, std)
            nets.load_state_dict(torch.load(RUN / f"s{s}_T.pt"))
            nets.eval()
            for p in nets.parameters():
                p.requires_grad_(False)
            pd0 = params_digest(nets)
            nets_by[s] = (nets, pd0)
            o = evaluate(torch, nets, goals, "O", None, caps)
            mism = [i for i, (a, b) in enumerate(zip(o, saved)) if a["words"] != b["words"] or a["end"] != b["end"]
                    or a["reach"] != b["reach"]]
            status["seeds"][str(s)]["baseline_mismatches"] = mism
            status["seeds"][str(s)]["O"] = o
            if mism:
                raise Stop(f"seed {s}: readout O does not reproduce the saved episodes ({len(mism)} mismatches)")
        status["memory"]["after_baseline"] = ph.mem()
        save("result_partial.json")
        # phase 3: readout R
        status["phase"] = "readout_R"
        for s in PROTOCOL["seeds"]:
            mean, std, goals, saved, rep_obs = data[s]
            nets, pd0 = nets_by[s]
            with torch.no_grad():
                rep_z = {g: nets.z(torch.from_numpy(ob)) for g, ob in rep_obs.items()}
            status["seeds"][str(s)]["R"] = evaluate(torch, nets, goals, "R", rep_z, caps)
            if params_digest(nets) != pd0:
                raise Stop(f"seed {s}: parameters changed")
            status["seeds"][str(s)]["params_unchanged"] = True
        status["memory"]["after_readout"] = ph.mem()
        # phase 4: diagnostics and decision
        status["phase"] = "diagnostics"
        for s in PROTOCOL["seeds"]:
            for arm in ("O", "R"):
                diagnose(status["seeds"][str(s)][arm])
            caps.check(f"diagnostics seed {s}")
        status["decision"] = decide(status)
        status["phase"] = "done"
    except Stop as ex:
        status["stopped"] = str(ex)
        status["decision"] = {"outcome": "stopped", "reason": str(ex)}
    save()
    for s in status["seeds"].values():
        for arm in ("O", "R"):
            for e in s.get(arm, []):
                e.pop("dist", None)
    save("result_compact.json")
    print(json.dumps(status["decision"], indent=1, default=float))
    return 0


def decide(status: Dict[str, Any]) -> Dict[str, Any]:
    D = PROTOCOL["decision"]
    per_seed = {}
    gains = losses = nO = nR = 0
    rows = []
    for s, sres in status["seeds"].items():
        o, r = sres["O"], sres["R"]
        a = sum(e["success"] for e in o)
        b = sum(e["success"] for e in r)
        per_seed[s] = {"n_O": a, "n_R": b, "gains": sum((y["success"] and not x["success"]) for x, y in zip(o, r)),
                       "losses": sum((x["success"] and not y["success"]) for x, y in zip(o, r))}
        nO += a
        nR += b
        gains += per_seed[s]["gains"]
        losses += per_seed[s]["losses"]
        for x, y in zip(o, r):
            rows.append({"seed": int(s), "cell": x["cell"], "air": x["cell"][2] == m.AIR, "O": x["success"],
                         "R": y["success"], "O_reach": x["reach"], "R_reach": y["reach"]})
    n = gains + losses
    p_sign = float(sum(__import__("math").comb(n, k) for k in range(gains, n + 1)) / 2 ** n) if n else 1.0
    confirm = nR >= 42 and losses <= 3 and all(v["n_R"] >= v["n_O"] for v in per_seed.values())
    reject = nR <= nO + 4
    outcome = "confirm" if confirm else ("reject" if reject else "inconclusive")
    split = {}
    for air in (True, False):
        sub = [x for x in rows if x["air"] == air]
        split["air" if air else "ground"] = {"goals": len(sub), "O": sum(x["O"] for x in sub),
                                             "R": sum(x["R"] for x in sub)}
    return {"outcome": outcome, "n_O": nO, "n_R": nR, "gains": gains, "losses": losses, "p_sign_one_sided": p_sign,
            "per_seed": per_seed, "split": split, "rule": {k: D[k] for k in ("confirm", "reject", "inconclusive")},
            "paired": rows}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["pin", "run"])
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args()
    out = a.out.resolve()
    if str(out).lower().startswith(str((REPO / "runs").resolve()).lower()):
        raise SystemExit("--out must be outside runs/")
    return cmd_pin(out) if a.cmd == "pin" else cmd_run(out)


if __name__ == "__main__":
    sys.exit(main())
