#!/usr/bin/env python3
"""Write the Explorer "Replay episode" .reg files for this checkout (writes files only; never touches the registry).

    python replay/make_context_menu_reg.py [--pythonw PATH]

Produces, next to this script:

    replay_context_menu_install.reg     adds the entry (HKEY_CURRENT_USER only, no admin rights)
    replay_context_menu_uninstall.reg   removes it again

A .reg file needs absolute paths, so rerun this after moving the repository
or changing the Python installation. Import is done by the user
(double-click the file, or `reg import <file>`).

The entry runs `pythonw replay_open.pyw "<item>"`:
  - on folders (every folder: Explorer offers no verified name filter here, so
    replay_open.pyw says so when a folder is not an episode), and
  - on files named exactly actions.jsonl (AppliesTo "System.FileName:=actions.jsonl").
MultiSelectModel=Single shows it only when exactly one item is selected, so a
multi-selection cannot start several games at once.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
OPENER = HERE / "replay_open.pyw"
ICON_EXE = REPO_ROOT / "build-us" / "Release" / "BattleShip.exe"
INSTALL = HERE / "replay_context_menu_install.reg"
UNINSTALL = HERE / "replay_context_menu_uninstall.reg"
VERB = "BattleShipReplay"
LABEL = "Replay episode"
KEYS = (
    ("Folders (every folder; one selected item)", r"HKEY_CURRENT_USER\Software\Classes\Directory\shell", None),
    ("Files named exactly actions.jsonl", r"HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.jsonl\shell",
     "System.FileName:=actions.jsonl"),
)


def reg_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def default_pythonw() -> Path:
    exe = Path(sys.executable)
    candidate = exe.with_name("pythonw.exe")
    return candidate if candidate.is_file() else exe


def write_reg(path: Path, lines: list) -> None:
    text = "\r\n".join(lines) + "\r\n"
    try:
        data = text.encode("ascii")
    except UnicodeEncodeError:  # regedit reads UTF-16 LE with a BOM for non-ASCII paths
        data = b"\xff\xfe" + text.encode("utf-16-le")
    path.write_bytes(data)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--pythonw", type=Path, default=default_pythonw(),
                    help="interpreter for the entry (default: pythonw.exe next to this Python)")
    args = ap.parse_args(argv)
    pythonw = args.pythonw.resolve()
    if not pythonw.is_file():
        ap.error(f"interpreter not found: {pythonw}")
    command = f'"{pythonw}" "{OPENER}" "%1"'
    install = [
        "Windows Registry Editor Version 5.00",
        "",
        f'; BattleShip replay viewer: "{LABEL}" in the Explorer right-click menu (current user only, no admin).',
        "; Generated by replay/make_context_menu_reg.py for:",
        f";   interpreter  {pythonw}",
        f";   opener       {OPENER}",
        "; Import: double-click this file (or `reg import <file>`). Remove: replay_context_menu_uninstall.reg.",
        '; Windows 11 lists classic entries under "Show more options" (Shift+F10).',
    ]
    for comment, base, applies_to in KEYS:
        key = f"{base}\\{VERB}"
        install += ["", f"; {comment}", f"[{key}]", f"@={reg_string(LABEL)}", f'"MultiSelectModel"={reg_string("Single")}']
        if applies_to:
            install.append(f'"AppliesTo"={reg_string(applies_to)}')
        if ICON_EXE.is_file():
            install.append(f'"Icon"={reg_string(f"{ICON_EXE},0")}')
        install += ["", f"[{key}\\command]", f"@={reg_string(command)}"]
    uninstall = [
        "Windows Registry Editor Version 5.00",
        "",
        f'; Removes the "{LABEL}" entries added by replay_context_menu_install.reg (current user only).',
        "; Empty parent keys created by the install (SystemFileAssociations\\.jsonl\\shell) are left in place.",
    ]
    for _, base, _ in KEYS:
        uninstall += ["", f"[-{base}\\{VERB}]"]
    write_reg(INSTALL, install)
    write_reg(UNINSTALL, uninstall)
    print(f"wrote {INSTALL}")
    print(f"wrote {UNINSTALL}")
    print(f"command: {command}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
